# Generated by Django 4.2.17 on 2024-12-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploaded_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileId', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file_format', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, upload_to='uploads')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
