# Generated by Django 4.2.17 on 2024-12-08 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaded_file',
            old_name='fileId',
            new_name='file_id',
        ),
        migrations.RenameField(
            model_name='uploaded_file',
            old_name='name',
            new_name='file_name',
        ),
    ]
