# Generated by Django 4.2.17 on 2025-01-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_correlationimage_edaimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlationimage',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='edaimage',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='correlationimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='correlation'),
        ),
        migrations.AlterField(
            model_name='edaimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='eda'),
        ),
    ]
