# Generated by Django 4.2.17 on 2025-01-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_correlationimage_name_edaimage_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorrelationImage',
        ),
        migrations.DeleteModel(
            name='EdaImage',
        ),
    ]
